version: "3.8"
services:
    mongodb:
        image: mongo:latest
        container_name: mongodb
        restart: always
        ports: 
            - 27018:27017
        volumes: 
            - data:/data
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=
            - MONGO_INITDB_ROOT_PASSWORD=
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=
            - ME_CONFIG_MONGODB_ADMINPASSWORD=
            - ME_CONFIG_MONGODB_SERVER=mongodb
    app:
        build: .
        ports:
            - 4000:3000
        depends_on:
            - mongodb
        environment:
            PORT: 3000
volumes: 
    data: {} 
    
networks:
    default: 
        name: mongodb_network
